// Generated by Selenium IDE
package selenium;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class AutomationpracticeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void automationpractice() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1461, 835));
    driver.findElement(By.id("search_query_top")).click();
    driver.findElement(By.id("search_query_top")).sendKeys("blouse");
    driver.findElement(By.name("submit_search")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    driver.findElement(By.xpath("/html/body/div/div[2]/div/div[3]/div[2]/ul/li/div/div[1]/div/a[1]")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    driver.findElement(By.name("Submit")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    driver.findElement(By.xpath("/html/body/div/div[1]/header/div[3]/div/div/div[4]/div[1]/div[2]/div[4]/a")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);





    //driver.findElement(By.cssSelector(".button-medium:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#SubmitCreate > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Random random = new Random();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("grupo01devops" + random.nextInt(500) + "@devops.cl");
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    driver.findElement(By.id("id_gender1")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("jose");
    driver.findElement(By.id("customer_lastname")).sendKeys("benavides");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("grupo01devops");
    driver.findElement(By.id("days")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    {
      WebElement dropdown = driver.findElement(By.id("days"));
     // dropdown.findElement(By.xpath("//option[. = 'regexp:10\\s+']")).click();
      dropdown.findElement(By.xpath("/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[6]/div/div[1]/div/select/option[10]")).click();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("days")).click();
    driver.findElement(By.id("months")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      //dropdown.findElement(By.xpath("//option[. = 'regexp:October\\s']")).click();
      dropdown.findElement(By.xpath("/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[6]/div/div[2]/div/select/option[11]")).click();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("months")).click();
    driver.findElement(By.id("years")).click();
    {
      WebElement dropdown = driver.findElement(By.id("years"));
     // dropdown.findElement(By.xpath("//option[. = 'regexp:1970\\s+']")).click();
      dropdown.findElement(By.xpath("/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[6]/div/div[3]/div/select/option[3]")).click();
    }
    driver.findElement(By.id("years")).click();
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("casa matriz usach 5555");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("santiago");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Alabama']")).click();
    }
    driver.findElement(By.id("id_state")).click();
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("666666");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.id("other")).click();
    driver.findElement(By.id("phone_mobile")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("phone_mobile")).sendKeys("56967676767");
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.id("alias")).sendKeys("direcciongrupo01 #444");
    driver.findElement(By.id("phone_mobile")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.id("postcode")).click();
    {
      WebElement element = driver.findElement(By.id("postcode"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    {
      WebElement element = driver.findElement(By.id("postcode"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("postcode"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("6666");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("grupo01devops");
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("66666");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.id("cgv")).click();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
  }
}
